//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVBuilder.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomSections
    {
        public int CustomSectionID { get; set; }
        public string SectionName { get; set; }
        public string Description { get; set; }
        public bool IsVisible { get; set; }
        public int ID_Curriculum { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
    }
}
