//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVBuilder.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVBuilderEntities : DbContext
    {
        public CVBuilderEntities()
            : base("name=CVBuilderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certificates> Certificates { get; set; }
        public virtual DbSet<Curriculum> Curriculum { get; set; }
        public virtual DbSet<CustomSections> CustomSections { get; set; }
        public virtual DbSet<Interests> Interests { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<PersonalReferences> PersonalReferences { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<Studies> Studies { get; set; }
        public virtual DbSet<Templates> Templates { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkExperiences> WorkExperiences { get; set; }
    }
}
