//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVBuilder.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalReferences
    {
        public int PersonalReferenceID { get; set; }
        public string Company { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<short> AreaCode { get; set; }
        public Nullable<int> Telephone { get; set; }
        public string Email { get; set; }
        public bool IsVisible { get; set; }
        public int ID_Curriculum { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
    }
}
