USE [master]
GO

/****** Object:  Database [CVBuilder]    Script Date: 09/08/2019 15:56:13 ******/
CREATE DATABASE [CVBuilder]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CVBuilder', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CVBuilder.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CVBuilder_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CVBuilder_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CVBuilder] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CVBuilder].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CVBuilder] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CVBuilder] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CVBuilder] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CVBuilder] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CVBuilder] SET ARITHABORT OFF 
GO

ALTER DATABASE [CVBuilder] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CVBuilder] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CVBuilder] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CVBuilder] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CVBuilder] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CVBuilder] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CVBuilder] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CVBuilder] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CVBuilder] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CVBuilder] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CVBuilder] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CVBuilder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CVBuilder] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CVBuilder] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CVBuilder] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CVBuilder] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CVBuilder] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CVBuilder] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CVBuilder] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CVBuilder] SET  MULTI_USER 
GO

ALTER DATABASE [CVBuilder] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CVBuilder] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CVBuilder] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CVBuilder] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CVBuilder] SET  READ_WRITE 
GO

